# Generated by Django 4.0 on 2021-12-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='img')),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
